export const FETCH_BOOKS_BEGIN = 'FETCH_BOOKS_BEGIN';
export const FETCH_BOOKS_SUCCES = 'FETCH_BOOKS_SUCCES';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
export const SAVE_BOOK_BEGIN = 'SAVE_BOOK_BEGIN';
export const SAVE_BOOK_SUCCES = 'SAVE_BOOK_SUCCES';
export const SAVE_BOOK_FAILURE = 'SAVE_BOOK_FAILURE';